STATE_TO_FIPS = {
    "US" : 0,
    "AL" : 1,
    "AK" : 2,
    "AS" : 60,
    "AZ" : 4,
    "AR" : 5,
    "CA" : 6,
    "CO" : 8,
    "CT" : 9,
    "DE" : 10,
    "DC" : 11,
    "FL" : 12,
    "FM" : 64,
    "GA" : 13,
    "GU" : 66,
    "HI" : 15,
    "ID" : 16,
    "IL" : 17,
    "IN" : 18,
    "IA" : 19,
    "KS" : 20,
    "KY" : 21,
    "LA" : 22,
    "ME" : 23,
    "MH" : 68,
    "MD" : 24,
    "MA" : 25,
    "MI" : 26,
    "MN" : 27,
    "MS" : 28,
    "MO" : 29,
    "MT" : 30,
    "NE" : 31,
    "NV" : 32,
    "NH" : 33,
    "NJ" : 34,
    "NM" : 35,
    "NY" : 36,
    "NC" : 37,
    "ND" : 38,
    "MP" : 69,
    "OH" : 39,
    "OK" : 40,
    "OR" : 41,
    "PW" : 70,
    "PA" : 42,
    "PR" : 72,
    "RI" : 44,
    "SC" : 45,
    "SD" : 46,
    "TN" : 47,
    "TX" : 48,
    "UM" : 74,
    "UT" : 49,
    "VT" : 50,
    "VA" : 51,
    "VI" : 78,
    "WA" : 53,
    "WV" : 54,
    "WI" : 55,
    "WY" : 56,
}

STATES_LONG_TO_SHORT = {
    "alabama" : "AL",
    "alaska" : "AK",
    "arizona" : "AZ",
    "arkansas" : "AR",
    "california" : "CA",
    "colorado" : "CO",
    "connecticut" : "CT",
    "delaware" : "DE",
    "district of columbia" : "DC",
    "d.c." : "DC",
    "florida" : "FL",
    "georgia" : "GA",
    "guam" : "GU",
    "hawaii" : "HI",
    "idaho" : "ID",
    "illinois" : "IL",
    "indiana" : "IN",
    "iowa" : "IA",
    "kansas" : "KS",
    "kentucky" : "KY",
    "louisiana" : "LA",
    "maine" : "ME",
    "marshall Islands" : "MH",
    "maryland" : "MD",
    "massachusetts" : "MA",
    "michigan" : "MI",
    "minnesota" : "MN",
    "mississippi" : "MS",
    "missouri" : "MO",
    "montana" : "MT",
    "nebraska" : "NE",
    "nevada" : "NV",
    "new hampshire" : "NH",
    "new jersey" : "NJ",
    "new mexico" : "NM",
    "new york" : "NY",
    "north carolina" : "NC",
    "north dakota" : "ND",
    "northern Mariana Islands" : "MP",
    "ohio" : "OH",
    "oklahoma" : "OK",
    "oregon" : "OR",
    "palau" : "PW",
    "pennsylvania" : "PA",
    "puerto Rrico" : "PR",
    "rhode island" : "RI",
    "south carolina" : "SC",
    "south dakota" : "SD",
    "tennessee" : "TN",
    "texas" : "TX",
    "united States" : "US",
    "utah" : "UT",
    "vermont" : "VT",
    "virginia" : "VA",
    "virgin islands" : "VI",
    "washington" : "WA",
    "west virginia" : "WV",
    "wisconsin" : "WI",
    "wyoming" : "WY"
}

SERIES_NAME_DICT ={
    "u3" : "ur", 
    "unemploment rate" : "ur", 
    "unemp rate" : "ur", 
    "ur" : "ur", 
    "u" : "u", 
    "e" : "e", 
    "employment" : "e", 
    "unemployment" : "u", 
    "total unemployed" : "u", 
    "unemployed" : "u", 
    "labor force" : "lf", 
    "lf" : "lf",
    "labor force participation rate" : "lfpr",
    "lfpr" : "lfpr"
}

FORMAT_STRING = {
    "state" : {
        "ur" : "LA{seas}ST{fips}0000000000003",
        "u" :  "LA{seas}ST{fips}0000000000004",
        "e" :  "LA{seas}ST{fips}0000000000005",
        "lf" : "LA{seas}ST{fips}0000000000006"
    },
    "us" : {
        "ur" :   "LN{seas}4000000",
        "u" :    "LN{seas}3000000",
        "e" :    "LN{seas}2000000",
        "lf" :   "LN{seas}1000000",
        "lfpr" : "LN{seas}1300000"
    }
}